### ISSUE TITLE
Separate package for openssl devel

### ISSUE THREAD

**Issue by antoineco** [ulyaoth/repository#1156]
Hey Sjir,

I'm using your openssl1.0.2 package to build Apache HTTPd on CentOS 7 (required for http/2 support), so first of all thanks for maintaining it! 

I was wondering if you would be willing to build a separate `-devel` package from your Specs for the development files, like in the base repo? This would allow discarding the `includes` after the build and keep only the runtime dependencies.

I can send a PR if that's something you would consider.

Ref: https://github.com/antoineco/httpd/blob/65ad3ae74e60ef9044fa1cc15e20e81cc522ea4a/2.4/centos/Dockerfile

Cheers

**Comment by sbagmeijer** [comment]
Hi I would really like to do that, i looked into this before but I did not fully understand how to get it splitted to a devel. 

If someone could show me some example how to do this then i deffinetly do this, I tried to look at how Fedora does it but their spec files are so bloated with stuff :(

**Comment by antoineco** [comment]
Sorry I haven't found the time to get back to this but I did read your answer and will try to get back to this issue ASAP.

**Comment by sbagmeijer** [comment]
Alright i have splitted the packages the exact same way Fedora does if I did some files in the wrong packages please give it a update and I will release a new version.

I should have this in the repository tonight or tomorrow.

It will look like this then:
OpenSSL 0.9.8
3.7M Mar 26 15:48 ulyaoth-openssl0.9.8-0.9.8zh-3.fc25.src.rpm
256K Mar 26 15:48 ulyaoth-openssl0.9.8-0.9.8zh-3.fc25.x86_64.rpm
523K Mar 26 15:48 ulyaoth-openssl0.9.8-devel-0.9.8zh-3.fc25.x86_64.rpm
745K Mar 26 15:48 ulyaoth-openssl0.9.8-libs-0.9.8zh-3.fc25.x86_64.rpm
17K Mar 26 15:48 ulyaoth-openssl0.9.8-perl-0.9.8zh-3.fc25.x86_64.rpm
736K Mar 26 15:48 ulyaoth-openssl0.9.8-static-0.9.8zh-3.fc25.x86_64.rpm

OpenSSL 1.0.0
3.9M Mar 26 15:46 ulyaoth-openssl1.0.0-1.0.0t-3.fc25.src.rpm
294K Mar 26 15:46 ulyaoth-openssl1.0.0-1.0.0t-3.fc25.x86_64.rpm
590K Mar 26 15:46 ulyaoth-openssl1.0.0-devel-1.0.0t-3.fc25.x86_64.rpm
881K Mar 26 15:46 ulyaoth-openssl1.0.0-libs-1.0.0t-3.fc25.x86_64.rpm
22K Mar 26 15:46 ulyaoth-openssl1.0.0-perl-1.0.0t-3.fc25.x86_64.rpm
848K Mar 26 15:46 ulyaoth-openssl1.0.0-static-1.0.0t-3.fc25.x86_64.rpm

OpenSSL 1.0.1
-rw-r--r--. 1 root root 4.4M Mar 26 15:44 ulyaoth-openssl1.0.1-1.0.1u-2.fc25.src.rpm
-rw-r--r--. 1 root root 309K Mar 26 15:44 ulyaoth-openssl1.0.1-1.0.1u-2.fc25.x86_64.rpm
-rw-r--r--. 1 root root 614K Mar 26 15:44 ulyaoth-openssl1.0.1-devel-1.0.1u-2.fc25.x86_64.rpm
-rw-r--r--. 1 root root 962K Mar 26 15:44 ulyaoth-openssl1.0.1-libs-1.0.1u-2.fc25.x86_64.rpm
-rw-r--r--. 1 root root  23K Mar 26 15:44 ulyaoth-openssl1.0.1-perl-1.0.1u-2.fc25.x86_64.rpm
-rw-r--r--. 1 root root 933K Mar 26 15:44 ulyaoth-openssl1.0.1-static-1.0.1u-2.fc25.x86_64.rpm

OpenSSL 1.0.2:
5.1M Mar 26 15:43 ulyaoth-openssl1.0.2-1.0.2k-2.fc25.src.rpm
326K Mar 26 15:43 ulyaoth-openssl1.0.2-1.0.2k-2.fc25.x86_64.rpm
690K Mar 26 15:43 ulyaoth-openssl1.0.2-devel-1.0.2k-2.fc25.x86_64.rpm
1.2M Mar 26 15:43 ulyaoth-openssl1.0.2-libs-1.0.2k-2.fc25.x86_64.rpm
24K Mar 26 15:43 ulyaoth-openssl1.0.2-perl-1.0.2k-2.fc25.x86_64.rpm
1.2M Mar 26 15:43 ulyaoth-openssl1.0.2-static-1.0.2k-2.fc25.x86_64.rpm

OpenSSL 1.1.0:
5.0M Mar 26 15:36 ulyaoth-openssl1.1.0-1.1.0e-1.fc25.src.rpm
1.4M Mar 26 15:36 ulyaoth-openssl1.1.0-1.1.0e-1.fc25.x86_64.rpm
892K Mar 26 15:36 ulyaoth-openssl1.1.0-devel-1.1.0e-1.fc25.x86_64.rpm
1.3M Mar 26 15:36 ulyaoth-openssl1.1.0-libs-1.1.0e-1.fc25.x86_64.rpm
22K Mar 26 15:36 ulyaoth-openssl1.1.0-perl-1.1.0e-1.fc25.x86_64.rpm
1.3M Mar 26 15:36 ulyaoth-openssl1.1.0-static-1.1.0e-1.fc25.x86_64.rpm


I hope that will fit for you :).

**Comment by antoineco** [comment]
Oh great! Let me give it a try. Sorry for taking so much time :(

**Comment by antoineco** [comment]
Alright I can confirm you I can build Apache 2.4 (httpd) with `mod_http2` support just fine using this new package split:
```
checking whether to enable mod_http2... checking dependencies
checking for OpenSSL... (cached) yes
  setting MOD_LDFLAGS to "-L/usr/local/ulyaoth/openssl1.0.2/lib   -lssl -lcrypto -lpthread -ldl"
  setting MOD_CFLAGS to "-I/usr/local/ulyaoth/openssl1.0.2/include  "
  setting MOD_CPPFLAGS to "-DH2_OPENSSL"
[...]
[root@f89f6a56dc7a ~]# /usr/local/apache2/bin/apachectl -M | grep http2
 http2_module (shared)
 proxy_http2_module (shared)
```
The file structure looks great!

The only thing I noticed is that man pages were installed although my Yum is configured with `tsflags=nodocs`. Could it be because you're installing them into a non-standard location?

Also beware that I tested only the `ulyaoth-openssl1.0.2`, `ulyaoth-openssl1.0.2-devel` and `ulyaoth-openssl1.0.2-libs` packages, but I don't think the structure changes that much between versions.

**Comment by antoineco** [comment]
I investigated the docs/man pages issue, and I found this in the [RPM documentation](http://rpm5.org/docs/rpm-guide.html)

> The %doc macro marks certain files as documentation. This allows the RPM to distinguish the files holding documentation from the other files in the RPM.

So in your case it should be enough the prepend the [following lines](https://github.com/sbagmeijer/repository/blob/ea3ef8b2da75ba28394cd4d883fdcd6e0f3e370e/ulyaoth-openssl/SPECS/ulyaoth-openssl1.0.2.spec#L108-L110) (in all packages) with the `%doc` keyword.

**Comment by sbagmeijer** [comment]
thank you very kind for the fix! I let all the builds rerun to have them correctly with the doc fix.

**Comment by sbagmeijer** [comment]
The OpenSSL splitted in multiple packages is now released and available.
Thank you for the help @antoineco and for the suggestion to do it this way! 👍

**Comment by antoineco** [comment]
Yeah I saw it yesterday and merged my changed (hence the 2 notifications above). Cheers @sbagmeijer! It's a real convenience for package management I think.
