### ISSUE TITLE
summary is incorrect for redis rpm

### ISSUE THREAD

**Issue by krm1312** [ulyaoth/repository#1165]
https://github.com/ulyaoth/repository/blob/master/ulyaoth-redis/SPECS/ulyaoth-redis3.spec#L30

ulyaoth-redis3.x86_64 : Tomcat native library

**Comment by sbagmeijer** [comment]
hehe thank you for noticing it :) copy paste error, I will fix it.

**Comment by sbagmeijer** [comment]
I will release the 3.2.8 version saturday it will have the summary correct. 
Thank you again for reporting it I appreciate the help.

**Comment by sbagmeijer** [comment]
Thank you again for the finding the issue, new Redis rpm has the correct summary so I shall close the issue 👍
