### ISSUE TITLE
Spotify - Facebook Login No Longer Supported

### ISSUE THREAD

**Issue by arod412** [ulyaoth/repository#1705]
When attempting to use the facebook login, it redirects to this link and output:

https://login.spotify.com/login-facebook-sso/?csrf=8b53b3a795629bbdf9fa8806250a2cab&port=4371

" Update Required

Facebook login for your Spotify client is no longer supported. Please upgrade to a newer version of Spotify. Download the latest version of Spotify at www.spotify.com/download. "

**Comment by sbagmeijer** [comment]
Hi I will have a look at this as soon as possible:

Reminder for myself new version is now located:
http://repository-origin.spotify.com/pool/non-free/s/spotify-client/

**Comment by arod412** [comment]
Hi,

Should I go ahead and test this on my end?

**Comment by sbagmeijer** [comment]
New version is in the repository, please try it and if you find any bugs feel free to submit a new issue.
