### ISSUE TITLE
Spotify - Browse tab not working

### ISSUE THREAD

**Issue by Yuji-Shimohira-Calvo** [ulyaoth/repository#1706]
Hi,

The "browse tab" that Spotify tries to open first by default is not working on my CentOS 7 machine. It used to work, it just stopped working recently and out of the blue.

If I click on "Browse" the client will show me some album covers three intermittent times, then it goes totally black.

The rest of tabs work just fine except for "social-feed." Not sure if this is related, but when clicked it says "Application is not installed." I am not concerned about this, just thought of reporting it in case it is related to the "Browse" tab issue.

Thanks a lot.

**Comment by Yuji-Shimohira-Calvo** [comment]
Hi again,

Thanks for the heads-up and no worries, I just thought there was something wrong with my installation. It isn't a breaking problem anyway :)

**Comment by sbagmeijer** [comment]
New version is in the repository, please try it and if you find any bugs feel free to submit a new issue.
