### ISSUE TITLE
Spotify unable to play videos

### ISSUE THREAD

**Issue by Yuji-Shimohira-Calvo** [ulyaoth/repository#1815]
Hi there,

I've recently noticed the client stops playing music when it hits a video in a curated playlist (probably Spotify's worst idea ever: adding videos to a music service, but whatever). I was wondering if you have in mind addressing this issue.

Thanks so much for your dedication to this repository!

**Comment by sbagmeijer** [comment]
I apologize there are multiple newer versions already available and we did not release them yet in the repository.

We will do our best to add the newer version tomorrow evening! :)

**Comment by Yuji-Shimohira-Calvo** [comment]
Thanks so much for the prompt reply!
