### ISSUE TITLE
Update hhvm rpms to version 3.10.1.

### ISSUE THREAD

**Issue by sbagmeijer** [ulyaoth/repository#43]
Update hhvm rpms to version 3.10.1.

**Comment by efriandika** [comment]
i have tried your yum hhvm 3.10.1
but i get "404 file not found". could you help me ?
i used nginx + hhvm..

**Comment by sbagmeijer** [comment]
Could you provide some more details on how you did set it up?

**Comment by efriandika** [comment]
i am using centos 7. Just install and run your package... but get file 404 not found
this is my nginx configuration:
    
    location ~ \.(hh|php)$ {
        fastcgi_keep_conn on;
        fastcgi_pass   127.0.0.1:9000;
    }

**Comment by sbagmeijer** [comment]
I noticed a small mistake in my rpm I will fix it in the next version after installing it you have to run:
chown -R hhvm:hhvm /etc/hhvm
chown -R hhvm:hhvm /var/cache/hhvm

##This are the steps I performed:##

yum install https://downloads.ulyaoth.net/rpm/CentOS/x86_64/ulyaoth-1.0.8-1.el7.centos.x86_64.rpm
yum install -y  http://mirror.nsc.liu.se/fedora-epel/7/x86_64/e/epel-release-7-5.noarch.rpm
yum install ulyaoth-nginx ulyaoth-hhvm
chown -R hhvm:hhvm /etc/hhvm
chown -R hhvm:hhvm /var/cache/hhvm

mkdir -p /srv/test
vi /srv/test/info.php

And I add:
```
<?php
phpinfo();
?>
```
chown 0644 /srv/test/info.php

Then as a test: hhvm /srv/test/info.php
(this works fine you see it spams with php.)


So let's try with nginx:

vi /etc/nginx/sites-available/info.conf

and I add:
```
server {
  listen 80;
  server_name info.ulyaoth.net;
  root /srv/test;

location ~ \.php$ {
  try_files $uri =404;
  fastcgi_pass 127.0.0.1:9000;
  include fastcgi_params;

  fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
}

location / {
}
}```

ln -s /etc/nginx/sites-available/info.conf /etc/nginx/sites-enabled/info.conf
systemctl start hhvm.service
systemctl start nginx.service

```
[root@centos7 ~]# curl -i -H "Host: info.ulyaoth.net" "http://127.0.0.1/info.php"
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 29 Oct 2015 07:39:06 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding

<html><head><title>HHVM phpinfo</title>
```
I hope that helps you!

**Comment by sbagmeijer** [comment]
All packages have been updated and are available in the repository: https://www.ulyaoth.net/resources/hhvm.21/

@efriandika if you require additional help please use my forum at:
https://www.ulyaoth.net/forums/repository-hhvm/

**Comment by efriandika** [comment]
I have solved this problem.
It caused by permission of doc root.
i use virtualmin, and doc root is /home/someuser/public_html
hhvm cannot access to the doc root, so by changing hhvm user or change permission can solve this problem
