### ISSUE TITLE
Please provide "latest" symlink for repository rpms

### ISSUE THREAD

**Issue by Hubbitus** [ulyaoth/repository#508]
Hello.

We use `ansible` for automatic orchestration.

Few days ago link to repository has been changed from:
```
https://downloads.ulyaoth.net/rpm/CentOS/x86_64/ulyaoth-1.0.10-1.el7.centos.x86_64.rpm
```
to
```
https://downloads.ulyaoth.net/rpm/ulyaoth-1.1.0-1.centos.noarch.rpm
```
Meantime make it `noarch` good idea.
I change it in playbook.

But yesterday it [again change version](https://www.ulyaoth.net/resources/ulyaoth-repository.6/update?update=272) and became:
```
https://downloads.ulyaoth.net/rpm/ulyaoth-1.1.2-1.centos.noarch.rpm
```
All again broken for automatic install.

Could you please provide convenient symlinks with static address for latest version like:
```
https://downloads.ulyaoth.net/rpm/ulyaoth-latest.centos.noarch.rpm
```
among others versioned files?

**Comment by sbagmeijer** [comment]
Hi that is a very good idea! I will do this tonight! :+1:

**Comment by sbagmeijer** [comment]
This is now available:

https://downloads.ulyaoth.net/rpm/ulyaoth-latest.centos.noarch.rpm
https://downloads.ulyaoth.net/rpm/ulyaoth-latest.fedora.noarch.rpm
https://downloads.ulyaoth.net/rpm/ulyaoth-latest.redhat.noarch.rpm
https://downloads.ulyaoth.net/rpm/ulyaoth-latest.scientificlinux.noarch.rpm
https://downloads.ulyaoth.net/rpm/ulyaoth-latest.oraclelinux.noarch.rpm
https://downloads.ulyaoth.net/rpm/ulyaoth-latest.amazonlinux.noarch.rpm

Thank you again for the suggestion!

**Comment by Hubbitus** [comment]
Thank you!
