### ISSUE TITLE
Update OpenSSL rpms to 1.0.2h and 1.0.1t

### ISSUE THREAD

**Issue by sbagmeijer** [ulyaoth/repository#551]
Update OpenSSL rpms to 1.0.2h and 1.0.1t

**Comment by NeckBeardPrince** [comment]
I assume this is why https://downloads.ulyaoth.net/ is down?

**Comment by sbagmeijer** [comment]
@NeckBeardPrince how do you mean down it works for me?

This issue is to create new rpms for openssl it should not affect the website itself (repository and website are fully seperate).

**Comment by sbagmeijer** [comment]
Packages have been created and will be available in our repository in the next few days.

OpenSSL 1.0.1: https://www.ulyaoth.net/resources/openssl-1-0-1.67/
OpenSSL 1.0.2: https://www.ulyaoth.net/resources/openssl-1-0-2.68/
