### ISSUE TITLE
Problems with ngx_http_headers_more_filter_module after upgrade to ulyaoth nginx 1.11.3

### ISSUE THREAD

**Issue by icarusninja** [ulyaoth/repository#794]
After upgrading to ulyaoth-nginx-mainline-1.11.3-1.el7.ngx.x86_64 from 1.9 I got the following nginx error:

 # nginx -t
nginx: [emerg] module "/etc/nginx/modules/ngx_http_headers_more_filter_module.so" version 1011001 instead of 1011003 in /etc/nginx/nginx.conf:13

After some troubleshooting, I got advised to downgrade to 1.11.1. This fixed the issue 

# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

Please fix this in upcoming versions. Best repo ever!

**Comment by sbagmeijer** [comment]
Hello  @icarusninja ,

Thank you for reporting the issue! it seems every nginx update requires a recompile of all modules I was not aware of this.

I was under the impression that you only have to compile it once and then it works for all versions but this does not seem to be the case.

I have now recompiled all modules against the latest nginx version so they should all work again.

Nginx: https://www.ulyaoth.net/resources/nginx-stable.24/
Nginx Mainline: https://www.ulyaoth.net/resources/nginx-mainline.25/
