### ISSUE TITLE
Updated spotify to 0.9.17.8.

### ISSUE THREAD

**Issue by sbagmeijer** [ulyaoth/repository#81]
Updated spotify to 0.9.17.8.
add Fedora 23 support.

**Comment by zackritter** [comment]
Fedora 23 is not working. It says that there's an error while solving dependencies when the update for the files and GPG key has to be downloaded.

**Comment by sbagmeijer** [comment]
This Should be available and updated: https://www.ulyaoth.net/resources/spotify.14/
