### ISSUE TITLE
install issue on fedora 24

### ISSUE THREAD

**Issue by victorsosa** [ulyaoth/repository#891]
Hi,

I am trying to install the package ulyaoth-nginx-passenger5 as the doc said, but I am getting the following error:

```
[deployer@carey ~]$ sudo dnf install https://downloads.ulyaoth.net/rpm/ulyaoth-latest.fedora.noarch.rpm -y
Last metadata expiration check: 2:07:01 ago on Sat Oct  8 15:12:24 2016.
Package ulyaoth-1.1.3-1.fedora.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[deployer@carey ~]$ sudo dnf install -y ulyaoth-nginx-passenger5 ulyaoth-nginx-passenger5-selinux
Last metadata expiration check: 2:07:22 ago on Sat Oct  8 15:12:24 2016.
No package ulyaoth-nginx-passenger5 available.
No package ulyaoth-nginx-passenger5-selinux available.
Error: Unable to find a match.
```

please let me know what else need to be done.

**Comment by sbagmeijer** [comment]
Hi I am afraid currently Fedora 24 is not in the list of supported operating systems:
https://www.ulyaoth.net/resources/passenger-5-nginx.26/

We will add it as soon as possible

**Comment by sbagmeijer** [comment]
I am afraid this is going to take longer then expected, the reason is that I changed all nginx related things to modules so trying to do this right and make a passenger module.

**Comment by victorsosa** [comment]
@sbagmeijer any update? please

**Comment by sbagmeijer** [comment]
sorry it took this long this is now available as a nginx module.

dnf install ulyaoth-nginx ulyaoth-nginx-module-passenger5

or

dnf install ulyaoth-nginx-mainline ulyaoth-nginx-mainline-module-passenger5

**Comment by victorsosa** [comment]
Thank you, 
I did the install but I am getting an issue similar to the one describe in this article:
https://stackoverflow.com/questions/16473586/403-forbidden-when-using-nginx-rails-passenger

**Comment by sbagmeijer** [comment]
@victorsosa I am not sure about that one sorry.

I have updated my guide how to use passenger try to follow that maybe it will help:
https://www.ulyaoth.net/resources/tutorial-how-to-install-nginx-with-passenger-on-fedora.37/

**Comment by sbagmeijer** [comment]
I will close the case new module is regular updated and we do not see any of the permission issues ourselves while using the rpms.

Thank you for the report we always appreciate the help :)
